version: '3.8'
services:
  app:
    build: .
    restart: always
    ports:
      - '8000:${PORT}'
    depends_on:
      - postgres
    environment:
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_EXPIRATION}
      - JWT_EXPIRATION=${JWT_EXPIRATION}

  postgres:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5433:5432'

volumes:
  postgres:
